# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boilerplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Бойлерплейт',
                'verbose_name_plural': 'Бойлерплейты',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('path', models.TextField(verbose_name='Путь до файла от корня')),
                ('content', models.TextField(null=True, verbose_name='Содержимое файла')),
                ('boilerplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='generator.Boilerplate', verbose_name='Бойлерплаейт')),
            ],
            options={
                'verbose_name': 'Файл в булерплейте',
                'verbose_name_plural': 'Файлы в булерплейте',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(verbose_name='Путь до папки от корня')),
                ('boilerplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='generator.Boilerplate', verbose_name='Бойлерплаейт')),
            ],
            options={
                'verbose_name': 'Папка в булерплейте',
                'verbose_name_plural': 'Папки в булерплейте',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguageCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('language', models.CharField(max_length=255, verbose_name='Название языка')),
                ('extension', models.CharField(max_length=255, verbose_name='Расширение файла')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='file',
            name='programming_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='generator.ProgrammingLanguageCode', verbose_name='Тип файла'),
        ),
    ]
